//users actions
export const UPDATE_RESPONSES = 'UPDATE_RESPONSES';
export const CLEAR_RESPONSES = 'CLEAR_RESPONSES';
export const SHOOT_VIDEO = 'SHOOT_VIDEO';
export const SELECT_EVENT = 'SELECT_EVENT';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const LOAD_EVENTS = 'LOAD_EVENTS';
export const GET_USER_CREDENTIALS = 'GET_USER_CREDENTIALS';
export const SELECT_ACCOUNT_TYPE = 'SELECT_ACCOUNT_TYPE';

export const LOGIN = 'LOGIN';
